
import React from 'react';
import {
    AlertCircle,
    AlertTriangle,
    Archive,
    Armchair,
    ArrowLeft,
    ArrowLeftRight,
    ArrowRight,
    BadgeCheck,
    Banknote,
    Battery,
    Bell,
    BellRing,
    BookOpen,
    Briefcase,
    Building2,
    Calendar,
    Camera,
    Car,
    Check,
    CheckCircle,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Circle,
    CircleDot,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Cog,
    Copy,
    Cpu,
    CreditCard,
    Database,
    Disc,
    DollarSign,
    Download,
    Droplet,
    Eraser,
    ExternalLink,
    Eye,
    EyeOff,
    Facebook,
    FileBarChart,
    FileText,
    Filter,
    Gem,
    Globe,
    Hammer,
    Gavel,
    HardDrive,
    Heart,
    HelpCircle,
    History,
    Home,
    Image,
    Info,
    Instagram,
    Key,
    Languages,
    Laptop,
    LayoutDashboard,
    LayoutGrid,
    Link,
    List,
    Loader,
    Lock,
    LogOut,
    Mail,
    MapPin,
    Maximize,
    Megaphone,
    Menu,
    MessageCircle,
    MessageSquare,
    Minus,
    MinusCircle,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Music,
    Navigation,
    Package,
    Paintbrush,
    PauseCircle,
    Pencil,
    Phone,
    Pipette,
    PlayCircle,
    Plus,
    PlusCircle,
    Power,
    Printer,
    Scissors,
    Search,
    Send,
    Settings,
    Settings2,
    Share2,
    Shield,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    Sliders,
    Snowflake,
    Sparkles,
    Speaker,
    Star,
    StopCircle,
    Store,
    Sun,
    SunDim,
    SunMoon,
    Syringe,
    Thermometer,
    Trash,
    Trash2,
    Truck,
    Upload,
    User,
    UserCheck,
    Users,
    Wallet,
    Warehouse,
    Waves,
    Wind,
    Wrench,
    X,
    XCircle,
    Zap,
    Gauge
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';

// Custom TikTok Icon
const TikTok = (props: LucideProps) => (
    <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
    >
        <path d="M9 12a4 4 0 1 0 4 4V4a5 5 0 0 0 5 5v4a9 9 0 0 1-9-9v9z" />
    </svg>
);

// Custom X (Twitter) Icon
const XLogo = (props: LucideProps) => (
    <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
    >
        <path d="M4 4l11.733 16h4.267l-11.733 -16z" />
        <path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772" />
    </svg>
);

const iconMap: Record<string, React.FC<LucideProps>> = {
    TikTok,
    'Twitter': XLogo,
    'XLogo': XLogo,
    'X': X, // Standard Close Icon
    'Close': X,
    AlertTriangle,
    Archive,
    Armchair,
    ArrowLeft,
    ArrowLeftRight,
    ArrowRight,
    BadgeCheck,
    Banknote,
    Battery,
    Bell,
    BellRing,
    BookOpen,
    Briefcase,
    Building2,
    Calendar,
    Camera,
    Car,
    Check,
    CheckCircle,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Circle,
    CircleDot,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Cog,
    Copy,
    Cpu,
    CreditCard,
    Database,
    Disc,
    DollarSign,
    Download,
    Droplet,
    Eraser,
    ExternalLink,
    Eye,
    EyeOff,
    Facebook,
    FileBarChart,
    FileText,
    Filter,
    Gem,
    Globe,
    Hammer,
    Gavel,
    HardDrive,
    Heart,
    HelpCircle,
    History,
    Home,
    'House': Home,
    Image,
    Info,
    Instagram,
    Key,
    Languages,
    Laptop,
    LayoutDashboard,
    LayoutGrid,
    Link,
    List,
    Loader,
    Lock,
    LogOut,
    Mail,
    MapPin,
    Maximize,
    Megaphone,
    Menu,
    MessageCircle,
    MessageSquare,
    Minus,
    MinusCircle,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Music,
    Navigation,
    Package,
    Paintbrush,
    PauseCircle,
    Pencil,
    Phone,
    Pipette,
    PlayCircle,
    Plus,
    PlusCircle,
    Power,
    Printer,
    Scissors,
    Search,
    Send,
    Settings,
    Settings2,
    Share2,
    Shield,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    Sliders,
    Snowflake,
    Sparkles,
    Speaker,
    Syringe,
    Star,
    StopCircle,
    Store,
    Sun,
    SunDim,
    SunMoon,
    Thermometer,
    Trash,
    Trash2,
    Truck,
    Upload,
    User,
    UserCheck,
    Users,
    Wallet,
    Warehouse,
    Waves,
    Wind,
    Wrench,

    XCircle,
    Zap,
    Gauge,
    // Aliases for modern names (compatibility)
    'CircleCheck': CheckCircle,
    'CircleX': XCircle,
    'CircleAlert': AlertCircle,
    'CircleHelp': HelpCircle,
    'CirclePlus': PlusCircle,
    'CircleMinus': MinusCircle,
    'CircleStop': StopCircle,
    'CirclePlay': PlayCircle,
    'CirclePause': PauseCircle,
    'TriangleAlert': AlertTriangle,
    'Edit': Pencil,
    'CircleUser': User,
    'SunOff': SunMoon,
    'SprayCan': Syringe,
    'towtruck': Truck,
};

interface IconProps extends Partial<Omit<LucideProps, 'ref'>> {
    name: string;
    className?: string;
}

const Icon = ({ name, ...props }: IconProps) => {
    const LucideIcon = iconMap[name];

    if (!LucideIcon) {
        // Fallback for icons not in the map
        return null;
    }

    return <LucideIcon {...props} />;
};

export default Icon;
