<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Oils & Fluids
            [
                'id' => Str::random(10),
                'name' => 'Castrol EDGE 5W-30 Synthetic Engine Oil',
                'description' => 'Premium full synthetic engine oil with Fluid Titanium Technology for maximum engine performance.',
                'price' => 45.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 150,
                'purchase_limit_per_buyer' => 10,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'oils',
                'store_subcategory_id' => 'engine-oil',
                'shipping_size' => 'm',
                'static_shipping_cost' => 5.00,
                'allowed_payment_methods' => json_encode(['cash', 'card', 'wallet']),
                'average_rating' => 4.7,
            ],
            [
                'id' => Str::random(10),
                'name' => 'Mobil 1 0W-40 Advanced Full Synthetic Motor Oil',
                'description' => 'Advanced full synthetic motor oil for superior engine protection at all temperatures.',
                'price' => 52.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 120,
                'purchase_limit_per_buyer' => 10,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'oils',
                'store_subcategory_id' => 'engine-oil',
                'shipping_size' => 'm',
                'static_shipping_cost' => 5.00,
                'allowed_payment_methods' => json_encode(['cash', 'card', 'wallet']),
                'average_rating' => 4.8,
            ],
            [
                'id' => Str::random(10),
                'name' => 'Valvoline ATF+4 Automatic Transmission Fluid',
                'description' => 'High-quality automatic transmission fluid for smooth shifting and extended transmission life.',
                'price' => 28.50,
                'media' => json_encode([]),
                'target_audience' => 'technicians',
                'specialty' => 'transmission-specialist',
                'total_stock' => 80,
                'purchase_limit_per_buyer' => 5,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'oils',
                'store_subcategory_id' => 'transmission-oil',
                'shipping_size' => 'm',
                'static_shipping_cost' => 5.00,
                'allowed_payment_methods' => json_encode(['cash', 'card', 'wallet']),
                'average_rating' => 4.5,
            ],

            // Filters
            [
                'id' => Str::random(10),
                'name' => 'Bosch Premium Oil Filter',
                'description' => 'Premium quality oil filter with 99% dirt-trapping efficiency for superior engine protection.',
                'price' => 12.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 300,
                'purchase_limit_per_buyer' => 20,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'filters',
                'store_subcategory_id' => 'oil-filter',
                'shipping_size' => 's',
                'static_shipping_cost' => 3.00,
                'allowed_payment_methods' => json_encode(['cash', 'card', 'wallet']),
                'average_rating' => 4.6,
            ],
            [
                'id' => Str::random(10),
                'name' => 'K&N High-Flow Air Filter',
                'description' => 'Washable, reusable air filter that improves acceleration and horsepower.',
                'price' => 59.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 100,
                'purchase_limit_per_buyer' => 5,
                'is_flash' => true,
                'expires_at' => now()->addDays(7),
                'store_category_id' => 'filters',
                'store_subcategory_id' => 'air-filter',
                'shipping_size' => 'm',
                'static_shipping_cost' => 4.00,
                'allowed_payment_methods' => json_encode(['cash', 'card', 'wallet']),
                'average_rating' => 4.9,
            ],

            // Batteries
            [
                'id' => Str::random(10),
                'name' => 'Bosch S4 Car Battery 12V 60Ah',
                'description' => 'Reliable car battery with excellent starting power and long service life.',
                'price' => 89.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 50,
                'purchase_limit_per_buyer' => 2,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'batteries',
                'store_subcategory_id' => 'car-battery',
                'shipping_size' => 'l',
                'static_shipping_cost' => 10.00,
                'allowed_payment_methods' => json_encode(['cash', 'card']),
                'average_rating' => 4.7,
            ],
            [
                'id' => Str::random(10),
                'name' => 'Varta Blue Dynamic 12V 74Ah',
                'description' => 'High-performance battery for vehicles with high electrical demands.',
                'price' => 129.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 40,
                'purchase_limit_per_buyer' => 2,
                'is_flash' => true,
                'expires_at' => now()->addDays(3),
                'store_category_id' => 'batteries',
                'store_subcategory_id' => 'car-battery',
                'shipping_size' => 'l',
                'static_shipping_cost' => 10.00,
                'allowed_payment_methods' => json_encode(['cash', 'card']),
                'average_rating' => 4.8,
            ],

            // Tires
            [
                'id' => Str::random(10),
                'name' => 'Michelin Pilot Sport 4 225/45R17',
                'description' => 'High-performance summer tire with excellent grip and handling.',
                'price' => 145.00,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 60,
                'purchase_limit_per_buyer' => 4,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'tires',
                'store_subcategory_id' => 'summer-tires',
                'shipping_size' => 'vl',
                'static_shipping_cost' => 15.00,
                'allowed_payment_methods' => json_encode(['cash', 'card']),
                'average_rating' => 4.9,
            ],
            [
                'id' => Str::random(10),
                'name' => 'Bridgestone Blizzak 205/55R16',
                'description' => 'Winter tire with superior ice and snow traction.',
                'price' => 125.00,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 80,
                'purchase_limit_per_buyer' => 4,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'tires',
                'store_subcategory_id' => 'winter-tires',
                'shipping_size' => 'vl',
                'static_shipping_cost' => 15.00,
                'allowed_payment_methods' => json_encode(['cash', 'card']),
                'average_rating' => 4.7,
            ],

            // Brakes
            [
                'id' => Str::random(10),
                'name' => 'Brembo Front Brake Pads',
                'description' => 'Premium brake pads for superior stopping power and minimal dust.',
                'price' => 75.00,
                'media' => json_encode([]),
                'target_audience' => 'technicians',
                'specialty' => 'brake-specialist',
                'total_stock' => 100,
                'purchase_limit_per_buyer' => 10,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'brakes',
                'store_subcategory_id' => 'brake-pads',
                'shipping_size' => 'm',
                'static_shipping_cost' => 5.00,
                'allowed_payment_methods' => json_encode(['cash', 'card', 'wallet']),
                'average_rating' => 4.8,
            ],
            [
                'id' => Str::random(10),
                'name' => 'ATE PowerDisc Brake Rotor Set',
                'description' => 'High-quality brake rotors for improved braking performance.',
                'price' => 149.99,
                'media' => json_encode([]),
                'target_audience' => 'technicians',
                'specialty' => 'brake-specialist',
                'total_stock' => 60,
                'purchase_limit_per_buyer' => 5,
                'is_flash' => true,
                'expires_at' => now()->addDays(5),
                'store_category_id' => 'brakes',
                'store_subcategory_id' => 'brake-discs',
                'shipping_size' => 'l',
                'static_shipping_cost' => 12.00,
                'allowed_payment_methods' => json_encode(['cash', 'card']),
                'average_rating' => 4.7,
            ],

            // Lighting
            [
                'id' => Str::random(10),
                'name' => 'Philips X-tremeVision LED Headlight H7',
                'description' => 'Ultra-bright LED headlight bulbs for maximum visibility and safety.',
                'price' => 89.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 150,
                'purchase_limit_per_buyer' => 4,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'lighting',
                'store_subcategory_id' => 'headlights',
                'shipping_size' => 's',
                'static_shipping_cost' => 4.00,
                'allowed_payment_methods' => json_encode(['cash', 'card', 'wallet']),
                'average_rating' => 4.6,
            ],
            [
                'id' => Str::random(10),
                'name' => 'Osram Night Breaker LED H4',
                'description' => 'Advanced LED technology for improved road illumination.',
                'price' => 79.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 120,
                'purchase_limit_per_buyer' => 4,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'lighting',
                'store_subcategory_id' => 'headlights',
                'shipping_size' => 's',
                'static_shipping_cost' => 4.00,
                'allowed_payment_methods' => json_encode(['cash', 'card', 'wallet']),
                'average_rating' => 4.5,
            ],

            // Accessories
            [
                'id' => Str::random(10),
                'name' => 'WeatherTech All-Weather Floor Mats',
                'description' => 'Custom-fit floor mats with deep channels to trap water, mud, and debris.',
                'price' => 119.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 80,
                'purchase_limit_per_buyer' => 2,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'accessories',
                'store_subcategory_id' => 'floor-mats',
                'shipping_size' => 'l',
                'static_shipping_cost' => 8.00,
                'allowed_payment_methods' => json_encode(['cash', 'card', 'wallet']),
                'average_rating' => 4.9,
            ],
            [
                'id' => Str::random(10),
                'name' => 'Luxury Leather Seat Covers Set',
                'description' => 'Premium leather seat covers for enhanced comfort and style.',
                'price' => 199.99,
                'media' => json_encode([]),
                'target_audience' => 'all',
                'specialty' => null,
                'total_stock' => 40,
                'purchase_limit_per_buyer' => 1,
                'is_flash' => true,
                'expires_at' => now()->addDays(10),
                'store_category_id' => 'accessories',
                'store_subcategory_id' => 'seat-covers',
                'shipping_size' => 'l',
                'static_shipping_cost' => 10.00,
                'allowed_payment_methods' => json_encode(['cash', 'card']),
                'average_rating' => 4.7,
            ],

            // Tools
            [
                'id' => Str::random(10),
                'name' => 'Craftsman 450-Piece Mechanic Tool Set',
                'description' => 'Comprehensive tool set for professional mechanics and DIY enthusiasts.',
                'price' => 299.99,
                'media' => json_encode([]),
                'target_audience' => 'technicians',
                'specialty' => 'mechanic',
                'total_stock' => 30,
                'purchase_limit_per_buyer' => 1,
                'is_flash' => false,
                'expires_at' => null,
                'store_category_id' => 'tools',
                'store_subcategory_id' => 'hand-tools',
                'shipping_size' => 'vl',
                'static_shipping_cost' => 20.00,
                'allowed_payment_methods' => json_encode(['cash', 'card']),
                'average_rating' => 4.8,
            ],
            [
                'id' => Str::random(10),
                'name' => 'Autel MaxiCOM MK808 Diagnostic Scanner',
                'description' => 'Professional automotive diagnostic tool with full system diagnosis.',
                'price' => 449.99,
                'media' => json_encode([]),
                'target_audience' => 'technicians',
                'specialty' => 'diagnostics',
                'total_stock' => 20,
                'purchase_limit_per_buyer' => 1,
                'is_flash' => true,
                'expires_at' => now()->addDays(14),
                'store_category_id' => 'tools',
                'store_subcategory_id' => 'diagnostic-tools',
                'shipping_size' => 'm',
                'static_shipping_cost' => 8.00,
                'allowed_payment_methods' => json_encode(['cash', 'card']),
                'average_rating' => 4.9,
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->insert(array_merge($product, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
